deploy-prod:
  stage: deploy
  script:
    - echo -e "https://mirrors.aliyun.com/alpine/v3.7/main" > /etc/apk/repositories
    - apk add sshpass
    - apk add openssh-client
    - rm -rf /var/lib/apt/lists/*
    - echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config 
    - echo " UserKnownHostsFile /dev/null" >> /etc/ssh/ssh_config
    - sshpass -p $bitblockhostpw scp -r * bit@$bitblockhostip:$pagelocation